### ISSUE TITLE
display.getClass().getMethod("getRawHeight");

### ISSUE THREAD

**Issue by BadDeveloper2022** [Jay-huangjie/EasyKeyBoardView#3]
这个方法是不是过期了？
每次调用这个方法报错
System.err: java.lang.NoSuchMethodException: getRawHeight []
        at java.lang.Class.getConstructorOrMethod(Class.java:472)
        at java.lang.Class.getMethod(Class.java:857)
        at com.jay.easykeyboard.constant.Util.getContentHeight(Util.java:135)
 W/System.err:     at com.jay.easykeyboard.base.KeyBoardEditText.init(KeyBoardEditText.java:56)
        at com.jay.easykeyboard.base.KeyBoardEditText.<init>(KeyBoardEditText.java:49)
        at com.jay.easykeyboard.SystemKeyBoardEditText.<init>(SystemKeyBoardEditText.java:41)
        at com.jay.easykeyboard.SystemKeyBoardEditText.<init>(SystemKeyBoardEditText.java:37)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)

操作系统:4.4.2

**Comment by Jay-huangjie** [comment]
@Sabirjan 应该是方法名过期了
