### ISSUE TITLE
为什么我是用setEditText方法时总是报on a null object reference

### ISSUE THREAD

**Issue by coly1194** [Jay-huangjie/EasyKeyBoardView#5]
调试时不是Null啊，走到这个方法就报错了。
![1574847835(1)](https://user-images.githubusercontent.com/45864761/69712391-b2489580-113d-11ea-9b88-b2db44d75c80.jpg)
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.oyon.ticketplatform, PID: 19712
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oyon.ticketplatform/com.oyon.ticketplatform.app_act.QRActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jay.easykeyboard.impl.SystemOnKeyboardActionListener.setEditText(android.widget.EditText)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jay.easykeyboard.impl.SystemOnKeyboardActionListener.setEditText(android.widget.EditText)' on a null object reference
        at com.jay.easykeyboard.SystemKeyboard.setEditText(SystemKeyboard.java:183)
        at com.jay.easykeyboard.SystemKeyboard.setEditText(SystemKeyboard.java:172)
        at com.oyon.ticketplatform.app_act.QRActivity.onCreate(QRActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by Jay-huangjie** [comment]
检查一下你在xml中是否设置了xmlLayoutResId哦，没有设置的话就没办法初始化了

**Comment by coly1194** [comment]
![image](https://user-images.githubusercontent.com/45864761/69785438-02cdfa80-11f3-11ea-81bf-38c1c065b38c.png)

我使用的是实例中的xml，xmlLayoutResId也设置了

**Comment by coly1194** [comment]
找到原因了keyboard:xmlLayoutResId="@xml/keyboard_numbers"  keybodard 关键字Studio自动导入了
